import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/styles.css"
const inter = Inter({ subsets: ["latin"] });
import { AccountAbstractionProvider } from '../context/accountContext'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><AccountAbstractionProvider>{children}</AccountAbstractionProvider></body>
    </html>
  );
}
